// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-eoNfyIPcoL5s49C_7qb61eGcV3uLtug',
    appId: '1:655928377445:web:d75cf0ba587e560ca5868c',
    messagingSenderId: '655928377445',
    projectId: 'cihuy12-3330b',
    authDomain: 'cihuy12-3330b.firebaseapp.com',
    storageBucket: 'cihuy12-3330b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt3UDca5ERsXFq2a_gDBD6uqu31b-viSU',
    appId: '1:655928377445:android:1fc244b2d1862232a5868c',
    messagingSenderId: '655928377445',
    projectId: 'cihuy12-3330b',
    storageBucket: 'cihuy12-3330b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-TW6BwUa03ouCCKp77bWeljoRZwLBGWQ',
    appId: '1:655928377445:ios:cb25782e7c770ea4a5868c',
    messagingSenderId: '655928377445',
    projectId: 'cihuy12-3330b',
    storageBucket: 'cihuy12-3330b.appspot.com',
    iosBundleId: 'com.example.firebaseKt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-TW6BwUa03ouCCKp77bWeljoRZwLBGWQ',
    appId: '1:655928377445:ios:cb25782e7c770ea4a5868c',
    messagingSenderId: '655928377445',
    projectId: 'cihuy12-3330b',
    storageBucket: 'cihuy12-3330b.appspot.com',
    iosBundleId: 'com.example.firebaseKt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-eoNfyIPcoL5s49C_7qb61eGcV3uLtug',
    appId: '1:655928377445:web:5199c3dcfb1dbadea5868c',
    messagingSenderId: '655928377445',
    projectId: 'cihuy12-3330b',
    authDomain: 'cihuy12-3330b.firebaseapp.com',
    storageBucket: 'cihuy12-3330b.appspot.com',
  );
}
